### PR TITLE
Add 'AODN-Portal' as the user agent for all proxied requests

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by pmbohm** [comment]
for https://github.com/aodn/backlog/issues/902

**Comment by pmbohm** [comment]
also see https://github.com/aodn/geoserver-build/pull/280

**Comment by lwgordonimos** [comment]
Could we add the version to the user agent as well? This seems to be the convention, and could be handy info?

e.g. `AodnPortal/v4.38.10`

**Comment by pmbohm** [comment]
Its possible
I think the convention of giving a version is so that the web service can adjust is response depending on the user-agent IE: chrome V 67.0 vs MS Internet Explorer v1

**Pull request merged**
