### PR TITLE
Remove DATA_COLLECTION_MODIFIED event as it is unused

### PR DESCRIPTION
**Pull request by dnahodil**

### CODE REVIEW

**Comment by jkburges** [comment]
Do we know what this used to be used for? We haven't inadvertently removed some functionality, have we?  Or just a hack-around?

**Comment by dnahodil** [comment]
It used to be used when data collections were rearranged. But we don't do that anymore.

**Comment by dnahodil** [comment]
See 861327666bead2a5b1aa476d47e3c6bd1893e5bb

**Comment by dnahodil** [comment]
Actually. Hold tight on this change.

**Comment by dnahodil** [comment]
There was another usage of this event which was removed. And it might be related to #1870.

**Comment by dnahodil** [comment]
Removed in 7b98dbcd4499c23c9cdd4b0d9f75bd976e0b20e9

**Pull request closed without merging**
