### PR TITLE
I, for one, welcome our new web crawling overlords

### PR DESCRIPTION
**Pull request by jkburges**

### CODE REVIEW

**Comment by danfruehauf** [comment]
No `robots.txt`? Means it'll return a 404 for that. Is that desirable?

**Comment by jkburges** [comment]
> No robots.txt? Means it'll return a 404 for that. Is that desirable?

Without one, crawlers will be free to crawl the entire website - which is ok for us (now).  The only reason we might want one (that I can think of) is to point crawlers to an xml `sitemap` - but do we have one?

**Comment by danfruehauf** [comment]
We actually do!

It's in sitemap.xml (https://imos.aodn.org.au/sitemap.xml)

**Comment by jkburges** [comment]
Ok let me change this then!

**Comment by jkburges** [comment]
Come to think of it, I think I helped work on that :-)

**Comment by jkburges** [comment]
Closing in favour of https://github.com/aodn/aodn-portal/pull/1815

**Pull request closed without merging**
