### PR TITLE
Fixes #2009

### LINKED ISSUE #2009: Step 3 does not render if accessed to quickly
App version: 4.15.3
            Build date: Tue Sep 29 12:17:44 AEST 2015
            Build number: 20
            Git ref: f5e30b566e43440ba6dc8c5632ae7ee7392ad2b6

Steps to reproduce:

Add any ACORN (ncwms) collection and when taken to step 2 immediately proceed to step 3

What should happen:

Step 3 is rendered and user sees collection name any filters should they be applied and download options

What does happen:

User sees a big blank white space.

Same as #1149 ?

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by dnahodil** [comment]
This change is good except the removal of the copyright header (unless there's something I'm missing?)

**Comment by pmbohm** [comment]
@jkburges Whats the policy on the copyright headers? I thought that they can/should be removed, although maybe I haven't been doing this always.

**Comment by dnahodil** [comment]
We're still waiting to get word from higher-up if we can remove the copyright headers (see https://github.com/aodn/aodn-portal/pull/1866)

**Comment by jachope** [comment]
Was sure that this had been signed-off by Pete in (see #1866) - maybe I should have put a comment.
My comment is that I am happy with what Pete suggests - my only concern was regarding if it was possible to grab/use code and not see the licence requirements further up a branch.

**Comment by dnahodil** [comment]
Oh sweet. Thanks, @jachope

**Pull request merged**
