### PR TITLE
Fix rebase problem

### PR DESCRIPTION
**Pull request by dnahodil**
Reinstate some changes which were lost in a rebase.

Also, added a default HTTP status for getMetadataAbstract as there were some code paths in which it wasn't set.

### CODE REVIEW

**Comment by danfruehauf** [comment]
Meh, my bad again.

**Comment by dnahodil** [comment]
It happens

**Comment by danfruehauf** [comment]
Still, embarrassing.

**Comment by anguss00** [comment]
I'll merge this @dnahodil, when Trav is finished

**Comment by anguss00** [comment]
Haha @danfruehauf is too fast on the trigger finger ;-)

**Pull request merged**
