### PR TITLE
local config at Config.local.groovy

### PR DESCRIPTION
**Pull request by danfruehauf**
allow loading of local config from grails-app/conf/Config.local.groovy if it
exists when in development mode. easier to amend config without needing to
touch the main Config.groovy

### CODE REVIEW

**Comment by dnahodil** [comment]
With this change can we get rid of the loading from environment variables for some settings?

It's best to have as few ways of setting/changes config as possible and (if I understand correctly) this new functionality would supersede what we were doing previously.

**Comment by danfruehauf** [comment]
I think it should be open for debate. Personally I like the ability to override a bunch of variables at a time (this is usually my use case). We also won't need to hold a table translating between a groovy config variable and an environment variable. So yes, I'd be happy to get rid of environment variables and use this method instead.

I can also do some more work to cleanup any references to environment variables, given we get a consensus about using this way.

Note that this is solely for dev mode though.

**Comment by dnahodil** [comment]
One problem with environment variables is that you need to add a new one for every setting you want to override. This solution means you can override any (and every) config in one go.

I don't know if IMAS (or anyone using our Portal software) use the environment variables or not. But I would think that the preferred setup would be for them to have a config groovy file (like we do in prod).

**Comment by danfruehauf** [comment]
IMAS wouldn't use environment variables - they just override everything in chef config.

So... I'll remove the environment variable overriding altogether, there shall be one way of overriding config (without touching the config file).

**Comment by danfruehauf** [comment]
Would you prefer it on a different commit, or squash it with the original one?

**Comment by danfruehauf** [comment]
@dnahodil So with the last commit there's no more `env[]` references.

**Comment by danfruehauf** [comment]
(Closed by accident)

**Pull request merged**
