### PR TITLE
fixes #1821 - layout manager internally properly updated when collections are deleted

### LINKED ISSUE #1821: Step 2 accordion - Sometimes newly-added collection is collapsed
Spotted today on edge
```
App version: 4.7.0
Build date: Tue Jun 30 13:27:21 AEST 2015
Build number: 31
Git ref: 30611e3956a5174167a9c5c74e65d0d34b2f5894
```

**Steps to reproduce**
* Add a collection to the map (I think any will work)
* Remove the collection using the cross icon in the accordion
* Return to step 1
* Add the same collection again
* Return to step 1
* Add another collection

**What does happen**
Both collections are collapsed in the accordion

**What should happen**
The last-added collection should be expanded

### PR DESCRIPTION
**Pull request by pmbohm**
Surplus expands and circular listeners removed

### CODE REVIEW

**Comment by pmbohm** [comment]
This also fixes the case where an accordion panel was deleted that was the currently expanded item and the no accordion panel is opened to replace it at the currently selected item

**Comment by danfruehauf** [comment]
Are there tests for this code? I think a test like "always expand last added collection" can be a good one.

It fixed the bug BTW, I verified it.

**Comment by pmbohm** [comment]
I dont see how i can test this. @danfruehauf

**Comment by danfruehauf** [comment]
You can test that `this.currentlyExpandedPanel` will be set to null when `onDestroy` is called, and verify the opposite for the other case. What do you think?

**Comment by pmbohm** [comment]
Test Ext.ux.NonCollapsingAccordionLayout directly?
That involves rendering items?

**Comment by danfruehauf** [comment]
You can mock whatever is going to emit errors because of rendering I believe.

**Comment by pmbohm** [comment]
I would need to actually render, as the logic in Ext.ux.NonCollapsingAccordionLayout kicks off when an item is added via 'renderItem'.

Anyway "What do I think?". No I dont see myself writing a jasmine test for this

**Comment by danfruehauf** [comment]
Alright.

**Pull request merged**
