### PR TITLE
Increase logging in order to debug travis hanging

### PR DESCRIPTION
**Pull request by jkburges**
e.g.: https://travis-ci.org/aodn/aodn-portal/builds/77101444

### CODE REVIEW

**Comment by jkburges** [comment]
Yes, it took me all morning just to figure out the correct way to configure this.

**Comment by jkburges** [comment]
I'd recommend merging this to master ASAP, even though I'm not sure it's actually fixing the problem.  But, if it *is* merged, and we don't see any travis hangs for several PRs, then perhaps we can say that it is fixed.

**Comment by dnahodil** [comment]
Did you want to rebase your changes to just reflect the final changes?

**Comment by jkburges** [comment]
Yeah that's a good idea.

**Comment by jkburges** [comment]
Done, although Murphy's Law says that this latest commit will hang.

**Comment by dnahodil** [comment]
To Hell with Murphy!

**Comment by dnahodil** [comment]
:8ball: Magic 8-ball says: Outlook is not good

**Comment by jkburges** [comment]
Boo. Don't bother merging this. :sob:

**Pull request closed without merging**
