### PR TITLE
Rounding off location co-ordinates

### PR DESCRIPTION
**Pull request by bhasin85**
The value of parameter I was not an integer and therefore some requests were failing.

**Invalid Request**

`http://geoserver-systest.aodn.org.au/geoserver/ncwms?LAYERS=acorn_hourly_avg_bonc_nonqc_timeseries_url%2Fsea_water_velocity&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=text%2Fxml&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=ncwms&REQUEST=GetFeatureInfo&STYLES=&QUERYABLE=true&CRS=EPSG%3A%204326&TIME=2016-09-27T22%3A00%3A00.000Z&BBOX=135.999756%2C-41.386475%2C145.83252%2C-34.19043&INFO_FORMAT=text%2Fxml&QUERY_LAYERS=acorn_hourly_avg_bonc_nonqc_timeseries_url%2Fsea_water_velocity&FEATURE_COUNT=1&SRS=EPSG%3A%204326&WIDTH=895&HEIGHT=655&X=205.00000000045532&Y=338&I=205.00000000045532&J=338&BUFFER=10`

`http://thredds-systest.aodn.org.au/thredds/wms/IMOS/ACORN/gridded_1h-avg-current-map_non-QC/BONC/2016/09/27/IMOS_ACORN_V_20160927T220000Z_BONC_FV00_1-hour-avg.nc?INFO_FORMAT=text%2Fxml&TIME=2016-09-27T22%3A00%3A00.000Z&BBOX=135.999756%2C-41.386475%2C145.83252%2C-34.19043&CRS=EPSG%3A+4326&QUERY_LAYERS=sea_water_velocity&SERVICE=ncwms&HEIGHT=655&REQUEST=GetFeatureInfo&I=205.00000000045532&STYLES=&J=338&WIDTH=895&BUFFER=10&FEATURE_COUNT=1&EXCEPTIONS=application%2Fvnd.ogc.se_xml&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=text%2Fxml&QUERYABLE=true&LAYERS=sea_water_velocity&Y=338&X=205.00000000045532&SRS=EPSG%3A+4326`

**Valid Request** 

`http://geoserver-systest.aodn.org.au/geoserver/ncwms?LAYERS=acorn_hourly_avg_bonc_nonqc_timeseries_url%2Fsea_water_velocity&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=text%2Fxml&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=ncwms&REQUEST=GetFeatureInfo&STYLES=&QUERYABLE=true&CRS=EPSG%3A%204326&TIME=2016-09-27T22%3A00%3A00.000Z&BBOX=135.999756%2C-41.386475%2C145.83252%2C-34.19043&INFO_FORMAT=text%2Fxml&QUERY_LAYERS=acorn_hourly_avg_bonc_nonqc_timeseries_url%2Fsea_water_velocity&FEATURE_COUNT=1&SRS=EPSG%3A%204326&WIDTH=895&HEIGHT=655&X=198&Y=329&I=198&J=329&BUFFER=10`

wms reference geoserver 2 9 x user manual

### CODE REVIEW

**Comment by anguss00** [comment]
I still can replicate the issue here though.... this issue is one where there's no validation when the user types a point coordinate that's outside the range of the dataset right?

**Comment by anguss00** [comment]
I can still recreate the issue when I click on a map point. On GFI click, the timeseries fields are pre-filled with the coord values at the click. As the timeseries panel has not been activated, the maxmin values are not set and the values validate.

**Comment by bhasin85** [comment]
@anguss00  I missed that condition. I have updated the code to validate after the minmax are set when the checkbox is clicked.

**Comment by anguss00** [comment]
Alright, looks great @bhasin85

**Pull request merged**
