### PR TITLE
google analytics for free text search facet

### PR DESCRIPTION
**Pull request by danfruehauf**

### CODE REVIEW

**Comment by dnahodil** [comment]
The change is fine. It should probably have a unit test, though.

**Comment by danfruehauf** [comment]
What do you want to test?

**Comment by dnahodil** [comment]
That trackFacetUsage is called with the expected values. Other GA trackings are unit tested.

**Comment by danfruehauf** [comment]
Sure.

**Comment by dnahodil** [comment]
It's not required but this might be a good time to enable free-text search in the development environment. If it'll be enabled in prod soon we might as well start seeing/using it. What do you reckon?

**Comment by danfruehauf** [comment]
> It's not required but this might be a good time to enable free-text search in the development environment. If it'll be enabled in prod soon we might as well start seeing/using it. What do you reckon?

Can do that. I'll amend the test and also the config part.

**Comment by danfruehauf** [comment]
@dnahodil GTG

**Pull request merged**
