### PR TITLE
disable flash checking in ext

### PR DESCRIPTION
**Pull request by danfruehauf**
fix for #1839. firefox has disabled flash, avoid the ugly popup
by not probing the flash version in the first place

sadly, there's no proper way to override this function as it is
called when the dom is loading

### CODE REVIEW

**Comment by danfruehauf** [comment]
I understand if we are going to be hesitant before merging that, however:
 * I don't think it's worth spending heaps of time on that
 * Probably doesn't happen on ext4/5/6
 * I doubt there's a better way to fix it, but please surprise me if there is

**Comment by dnahodil** [comment]
I don't know of a better way to fix this, either.

I assume the ext-all.js change is the same?

**Comment by danfruehauf** [comment]
Yeah, `ext-all.js` fixed as well manually. I just took the parenthesis away so the function is not called (`swfobject`).

Please do check me though. Please verify this fix works also for you (I tested only on newest Firefox and made sure I don't get the flash artifact showing).

**Comment by dnahodil** [comment]
Yep. I'll check it out.

**Comment by dnahodil** [comment]
Looks good, @danfruehauf

**Pull request merged**
