### PR TITLE
Point time series feature

### PR DESCRIPTION
**Pull request by jonescc**

### CODE REVIEW

**Comment by bhasin85** [comment]
Please see the screenshot for the error details.

pull request craig

**Comment by jonescc** [comment]
@bhasin85 -  issue with non-timeseries subset fixed

**Comment by bhasin85** [comment]
@jonescc  Sorry Craig, somehow I am unable to get the CSV option for _"IMOS - ACORN - Rottnest Shelf HF ocean radar site (Western Australia, Australia) - Delayed mode sea water velocity"_ when I select **Point timeseries**

. 

craig 2

**Comment by jonescc** [comment]
Thanks @bhasin85, my last fix not quite right.  I've fixed the issue and added a unit test to make sure it doesn't happen again.

**Comment by jonescc** [comment]
@bhasin85 - modified ncwms panel to only display time series at a point option for collections supporting download of time series at a point

**Comment by jonescc** [comment]
Hold on a moment something went awry with my last push.  Let me make sure all changes are pushed up.

**Comment by jonescc** [comment]
OK, should be OK now.  Didn't actually push my changes before

**Comment by jonescc** [comment]
OK, looks like some issues with htmlunit tests.  Let me sort that out

**Comment by jonescc** [comment]
@bhasin85 - htmunit issues resolved.

**Comment by bhasin85** [comment]
It looks good to me :smile:  @jonescc  Craig!

**Pull request merged**
