### PR TITLE
Upgrade to JQuery3

### PR DESCRIPTION
**Pull request by pmbohm**
@bhasin85 I need a hand to fix a clash with Selinium!

### CODE REVIEW

**Comment by julian1** [comment]
This is likely to be a bit risky no?

**Comment by bhasin85** [comment]
Sure @pmbohm  ... We can work on it together.

**Comment by pmbohm** [comment]
@bhasin85 fixed tests now. Maven/Travis uses the uncompressed jQuery where i have comment out a workaround for Safari. BTW it works in Safari, although Safari is an "unsupported browser"

**Comment by akashisama** [comment]
Fixes #2451

**Comment by akashisama** [comment]
A bunch of random tests are failing in the currently running selenium build. I'm guessing it's related to the jquery upgrade. I'll have a look.

**Pull request merged**
