### PR TITLE
New helper function for testing

### PR DESCRIPTION
**Pull request by dnahodil**
I get really sick of writing anonymous functions in the Jasmine tests. Would people be happy using this helper? **I don't *think* this would be controversial but maybe we get the okay from 2 devs before we merge this?**

Essentially instead of writing: (Which happens heaps in test specs)
``` javascript
var testLayer = {
    isNcwms: function() { return true }
}
```
You can just write:
``` javascript
var testLayer = {
    isNcwms: returns(true)
}
```

Note, it can't be used if the variable being returned will change after the function is created. In that case you'd need to write the anonymous function the old-fashioned way. I think there were about 3 cases of this is the current test suites.

### CODE REVIEW

**Comment by danfruehauf** [comment]
As said before - OK from me.

**Comment by dnahodil** [comment]
@jkburges any thoughts?

**Comment by jkburges** [comment]
I think it's good :+1:

**Comment by dnahodil** [comment]
Thanks guys. If someone could merge, then, please?

**Comment by jkburges** [comment]
image

**Comment by jkburges** [comment]
Sorry, I'm feeling a bit emotional w.r.t. to git after a bad rebase experience.

**Comment by dnahodil** [comment]
:-1: we should stuck with SVN...

**Pull request merged**
