### PR TITLE
 Allow onlineResources with protocol 'WWW:LINK-1.0-http--downloaddata' on Step 3

### LINKED ISSUE #2106: Links to Acoustic Data Viewer not showing on Step 3
## Steps to reproduce
1. Select ANMN Passive Acoustic Observatories Sub-facility
1. Go to step 3

## What I expect
A link to the acoustic data viewer - so that I can download the data 

## What happens
No link

See: https://github.com/aodn/content/issues/147#issuecomment-171520055

### PR DESCRIPTION
**Pull request by pmbohm**
Fixes #2106
Fixes https://github.com/aodn/backlog/issues/270

### CODE REVIEW

**Comment by anguss00** [comment]
When I test this, I'm getting the new AODN landing page on load @pmbohm. We may have to cherry-pick this commit across post my revert commit being merged to master.

**Comment by anguss00** [comment]
But works as expected aside from that. Just to check, we expect to go direct to the ANMN acoustics app home page right @pmbohm?

**Comment by pmbohm** [comment]
@anguss00 It will go to where ever the links will takes us! We are asking the links to take us to a new tab as well so the user gets no unwanted surprise

**Comment by anguss00** [comment]
Cool, sounds good to me

**Pull request merged**
