### PR TITLE
Updated event Primary and Secondry. Added getfeatureInfoAnchorTrackin…

### PR DESCRIPTION
**Pull request by bhasin85**
…gCategory in en.js

### CODE REVIEW

**Comment by bhasin85** [comment]
@anguss00  Ready for review :+1:

**Comment by anguss00** [comment]
Audited all of the existing events @pblain. Looks good from this end

**Comment by bhasin85** [comment]
Thanks Angus!
giphy

**Comment by pblain** [comment]
Excellent

**Pull request merged**
