### PR TITLE
refactor search facets creation

### PR DESCRIPTION
**Pull request by danfruehauf**
can specify facets in server config

makes it easier to choose which facets to load for which portals. easier to incorporate things like https://github.com/aodn/aodn-portal/pull/1745

@markhepburn FYI

### CODE REVIEW

**Comment by pmbohm** [comment]
@danfruehauf  needs work on the title inside 9eaad3b

**Comment by danfruehauf** [comment]
@pmbohm Yep. Talking to @markhepburn about it.

**Comment by danfruehauf** [comment]
@pmbohm It's good now. I rearranged the commits so they do not contain those weird lines.

**Comment by danfruehauf** [comment]
Tests will fail, working on that.

**Comment by pmbohm** [comment]
@danfruehauf comments

**Comment by danfruehauf** [comment]
Fixed the copyright, the comma can stay, it's harmless.

**Pull request merged**
