### PR TITLE
No DB

### PR DESCRIPTION
**Pull request by danfruehauf**
Fully stateless portal - DB stripped out.

Things that were removed:
 * DB - No more DB whatsoever, no more hibernate, no GORM
   * This entails also no AODAAC
 * ~20K lines of code

How do filters work?
 * Dynamically via geoserver (`featureToggles/dynamicFilters = true`)
 * Statically from the filesystem (`featureToggles/dynamicFilters = false`)

If the static option is chosen, filters are taken from `filters/LAYER_WORKSPACE/LAYER_NAME/filters.xml`.

How to get the filters (transform from JSON to XML and store locally):
```
./get_filters.rb -u https://catalogue-123.aodn.org.au/geonetwork -g http://geoserver-123.aodn.org.au/geoserver/wms -p https://imos.aodn.org.au/imos123 -d filters
```

Ready to be reviewed and merge.

### CODE REVIEW

**Comment by danfruehauf** [comment]
@dnahodil I'm retaking control of this branch. I'll do the daily rebases.

**Comment by danfruehauf** [comment]
This PR is now game.

I cherry-picked the commits from no_db that didn't make it into the filters rework.

**Comment by danfruehauf** [comment]
@dnahodil Kudos for a clean work on the filters branch, it made this rebase/cherry-pick much easier.

**Comment by dnahodil** [comment]
Thanks @danfruehauf. Happy to hear that.

**Comment by danfruehauf** [comment]
BTW, this branch is alive at https://edge.aodn.org.au/no_db

**Comment by dnahodil** [comment]
@danfruehauf if you want to rebase this I'll start reviewing it.

**Comment by danfruehauf** [comment]
Already rebased, just running unit tests + some manual sanity testing.

**Comment by danfruehauf** [comment]
It's looking fine from my end (filters from files).

**Comment by danfruehauf** [comment]
I'm thinking perhaps we can bump a major version here.

**Comment by dnahodil** [comment]
I think a major version bump would be a good idea.

**Comment by danfruehauf** [comment]
+ new jenkins pipeline?

**Comment by dnahodil** [comment]
In Config.groovy we should egt rid of the logging configuration for UserTagLib, AuthController, LayerService and MenuJSONCache which have all been removed.

**Comment by danfruehauf** [comment]
@dnahodil I'll remove those. Prefer them in a separate commit, or squash it with the original?

**Comment by dnahodil** [comment]
Separate, I'd say.

I have a few other comments coming, I've just got distracted.

**Comment by dnahodil** [comment]
LayerController line 114 should just read `else {`

**Comment by dnahodil** [comment]
The logging on lines 260 and 261 of DownloadController should be removed

**Comment by danfruehauf** [comment]
The layer controller error is a rebase mistake. Thanks for picking that up.

**Comment by dnahodil** [comment]
That's alright, I expected us to have a few of those

**Comment by dnahodil** [comment]
There's a variable called `allowedMethods` in LayerController and Server controller which can be removed as they're no longer relevant.

**Comment by dnahodil** [comment]
I noticed we've used placeholders to keep the 'domain' and 'migrations' directories. Do we still need those? I'd say get rid of those directories (as long as Grails doesn't care).

**Comment by danfruehauf** [comment]
Grails does care about those directories :/

It works, but outputs many many errors. I can show you, or you can experiment on your own. Both for the migrations and domains.

**Comment by dnahodil** [comment]
The `_filtersForLayer` method can be removed from GeoserverServer now as it was only for database layers.

**Comment by dnahodil** [comment]
I'm surprised about the migrations directory because we've removed the migrations plugin. It's less surprising that it expects the domain directory to be there.

But that's fine, they can stay.

**Comment by danfruehauf** [comment]
Yep. I'm following up on all of those - don't worry. That was a rebase mistake as well.

**Comment by dnahodil** [comment]
So my last comment is that I think the default for dynamic filters should be 'true'. In most cases we'll want to load filters from GeoServer and it is also the easiest way for people to get a Portal up and going.

**Comment by danfruehauf** [comment]
BTW, I think grails 2.x and 3.x wouldn't care about the lack of domain/migraions directories. Upgrading to 2.x should be easy. To 3.x there's more effort required.

**Comment by danfruehauf** [comment]
@dnahodil All addressed at: https://github.com/aodn/aodn-portal/commit/6643e55c20eda68875c1959976a8400501f5f50b

Except for the rebase mistake, which I amended to the original commit.

**Comment by dnahodil** [comment]
@danfruehauf did we have anything planned to replace MOTD? If Portal were released like this we wouldn't have the ability to present messages to the user like we used to (although maybe in a less intrusive way). We'll need a solution that allows Kate to put up messages without developer intervention.

**Comment by danfruehauf** [comment]
Oh, that's correct. Completely forgot about that...

Hopefully no downtime?

Umn. Perhaps @pblain can decide on that.

**Comment by dnahodil** [comment]
We might need to have a talk about options. I mentioned it to @pblain because I couldn't remember if we'd decided anything about it and he didn't pointed out that making a big change to the Portal is an important time to be able to have that functionality.

**Comment by danfruehauf** [comment]
The idea was to have the status page by now. It obviously fell somewhere behind in the backlog.

**Comment by danfruehauf** [comment]
@dnahodil Just had a chat with @pblain - a rudimentary MOTD should suffice. I'll get the functionality back + implement it to fetch a URL from config. If the URL is empty/unavailable - no MOTD. If the URL returns something - just plant it in the box like before.

**Comment by danfruehauf** [comment]
@dnahodil Travis failed, saw that, I'm fixing that. I think you can still provide feedback on that MOTD commit.

**Comment by dnahodil** [comment]
MOTD commit looks okay. I just made a couple of notes, but I'm not going to suggest we make more changes that that.

**Comment by danfruehauf** [comment]
Lets have another reason to drink beer today. :)

**Comment by dnahodil** [comment]
> Lets have another reason to drink beer today. :)

Agreed!

**Comment by danfruehauf** [comment]
OMG OMG OMG OMG

**Comment by danfruehauf** [comment]
LOL.

**Comment by anguss00** [comment]
:+1:

**Comment by danfruehauf** [comment]
Relief:
```
[dan@keke (master) aodn-portal]$ git br -d no_db
Deleted branch no_db (was a8100f6).
[dan@keke (master) aodn-portal]$ 
```

**Comment by tojofo** [comment]
doubledreamhands

**Pull request merged**
