### PR TITLE
Geoserver filters feature toggle

### PR DESCRIPTION
**Pull request by dnahodil**
This adds a feature toggle to select between loading filters from the database and loading them from XML files/GeoServer. For now we use XML files (ie. not GeoServer) but that can be easily changed when the new GeoServer plugin changes have been made.

### CODE REVIEW

**Comment by dnahodil** [comment]
Still has some println()s in there but I can grab them out later.

**Comment by anguss00** [comment]
Looks good @dnahodil :+1:

**Comment by anguss00** [comment]
Actually, I've just found an issue with filterPanels not being created correctly when accessing from xml files that I'll need to ask you about on tuesday @dnahodil

**Comment by dnahodil** [comment]
@anguss00 I've pushed up a change to the get_filters.rb script which should fix the type problem you found. It will still be broken until we do the conversion from GeoServer -> Portal filter types. That work is already started on another branch so we should see it soon.

**Comment by anguss00** [comment]
Ok no worries @dnahodil, I'll merge this when Trav is finished

**Pull request merged**
