### PR TITLE
Revert the snazo user interface (for now)

### PR DESCRIPTION
**Pull request by anguss00**
Snazo lives on in the branch named "snazo"

### CODE REVIEW

**Comment by dnahodil** [comment]
C'est la vie

**Comment by dnahodil** [comment]
No. that's not what I meant. What's the other one.

Ah.

Such is life.

**Comment by dnahodil** [comment]
No, I was right.

**Comment by anguss00** [comment]
it's alright, snazo will rise like a phoenix from the ashes soon...

**Pull request merged**
