### PR TITLE
Default mail config. Created for WPS

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by danfruehauf** [comment]
Why is that required? Should be switched on only for production/test environments. By default, for dev it should be disabled as it is now.

**Comment by pmbohm** [comment]
No idea. I'm copying closely https://github.com/aodn/go-go-duck/blob/master/grails-app/conf/Config.groovy#L50 for WPS
Does that mean go-go-duck is incorrect/ unsafe?

**Comment by danfruehauf** [comment]
Probably the config there was redundant. Who has a mail service running on their host anyway? :)

**Comment by pmbohm** [comment]
I'll put up a pull request to remove it from go-go-duck then

**Pull request closed without merging**
