### PR TITLE
Tooltip hover labels for faceted search result icons

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by pmbohm** [comment]
Fixes #2487

**Comment by akashisama** [comment]
I think it would be better to keep the tooltip names the same as the names used in the facets, to emphasise that they're the same thing. ie "Parameter", "Organisation", "Platform"

**Comment by pmbohm** [comment]
I see it as an opportunity to give a long hand explanation of "Parameter" and "Platform" in particular. 

And i was thinking along the lines of this to help solve the connection to the facets https://github.com/aodn/backlog/issues/639

**Comment by akashisama** [comment]
If we do add that feature then I think it will make even more sense to use the same labels for both.

**Pull request merged**
