### PR TITLE
Openlayers 2.13.1

### PR DESCRIPTION
**Pull request by danfruehauf**
**Not to merge yet**

OpenLayers 2.13.1 upgrade. Includes:
 * OpenLayers 2.13.1 source code, replacing the 2.10 version (first commit)
 * Various fixes such as adjusting tests, fixing i18n
 * Remove unused class TemporalMap
 * Remove IE compatibility code
 * All OpenLayers CSS customizations are now externalized to the OpenLayers 2.13.1 directory
 * Shows error when drawing  a bbox over the ante meridian (because otherwise it'd be possible)

### CODE REVIEW

**Comment by danfruehauf** [comment]
When reviewing that, do not review the first giant commit. That's the OpenLayers 2.10 -> 2.13.1 replacement.

And this also fixes #1730.

**Comment by dnahodil** [comment]
We need to remember to update @kereid's test cases with the new open layers. Filtering over the anti-meridian, for instance, will need some tests devised.

**Comment by danfruehauf** [comment]
Will do.

Although we first need to think /what/ we are going to do with this new feature. We might decide to prohibit users from drawing those boxes...

**Comment by danfruehauf** [comment]
I think... lets have someone review this now because it's already a fair few commits. I think this is merge-able considering the only problem is when drawing a box over the anti-meridian. This can be addressed in another issue and still needs some thought put into it. So... Ready to be reviewed.

**Comment by dnahodil** [comment]
I would say that we can't merge this at the moment. We either need to fix filtering and downloads with a  geogrpahic boundary over the antimeridian (for both WMS and ncWMS) *or* we need to do something to prevent those boxes being drawn. It might seem odd, buthaving downloads which are silently incorrect is a worse bug than the current situation (i.e. not being able to draw a box over the antimeridian - but at least that's obvious).

It can certainly start being reviewed.

**Comment by danfruehauf** [comment]
What did I break now...

**Comment by danfruehauf** [comment]
@pmbohm GTG.

**Comment by pmbohm** [comment]
@danfruehauf merged

**Pull request merged**
