### PR TITLE
Step1 button enhancements

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by dnahodil** [comment]
Is there any way we can extract that font-awesome html fragment so that we only need to define it once or twice instead of having it spread in a dozen different places?

**Comment by pmbohm** [comment]
Yes ok where possible (non gsp places) I'll do it. Maybe a super css class of our own that does what 'fa fa-fw fa-external is doing is cleaner simpler? @dnahodil

**Comment by pmbohm** [comment]
Using the 'external' css style now will get the same Bootstrap Fontawesome effect as appending a span with "fa fa-fw fa-external-link' classes. The css class method is more simple to apply using gsp's or javascript

**Comment by dnahodil** [comment]
This appears to add unwanted spacing to the right hand side of links which are within a paragraph of text (see the landing page).

**Comment by pmbohm** [comment]
@dnahodil Disgusting unwanted spacing removed :)
I did look earlier at the landing page, just not when it really mattered.

**Pull request merged**
