### PR TITLE
Now handles null defaultPalettes from thredds ncWMS server

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by pmbohm** [comment]
It is not possible to get the default Palette information cheaply from a Thredds ncWMS server. So the portal changes here can gracefully handle this.

**Comment by pmbohm** [comment]
Referencing #305 - ncWMS can give us defaultPalette however Thredds ncWMS is missing this functionality, as no index is built

**Comment by danfruehauf** [comment]
I'll add that generally `GetCapabilities` is lacking that. Gives the styles, but not the default one. Not sure if the `GetMetadata` request that ncwms actually does is part of OGC WMS. @jonescc ??

**Comment by dnahodil** [comment]
Nah, `GetMetadata` is not part of the WMS spec. It's something that ncWMS added.

**Comment by danfruehauf** [comment]
So I assume it's OK for us to interact with `GetMetadata` on a "best effort" basis. We cannot actually get all the information we need out of thredds, as @pmbohm mentioned.

**Comment by dnahodil** [comment]
I don't think we use `GetMetadata` for much. It might be simpler to assume it's *never* available and just do the same for stand-alone ncWMS as we do for THREDDS ncWMS.

**Comment by danfruehauf** [comment]
@dnahodil `GetMadata` is used for 3 things (I don't think more):
 * Getting styles (`REQUEST=GetMetadata&item=layerDetails`)
 * Getting all available days with data (`REQUEST=GetMetadata&item=layerDetails`)
 * Getting timesteps for day (`REQUEST=GetMetadata&item=timesteps`)

**Comment by dnahodil** [comment]
Okay, so the only one that we can't get with the ncWMS plugin is styles (default style/palette, really). So maybe we change this code to behave as if we can never have this information?

**Comment by danfruehauf** [comment]
As discussed - I'm happy with that. So a blank box to start with after load?

**Comment by dnahodil** [comment]
I think @pmbohm has set some default text which is probably better than blank. I think this is the code that can be simplified: https://github.com/aodn/aodn-portal/pull/2040/files#diff-f562570827825bf3c38891d4fb397849R119

**Comment by pmbohm** [comment]
Heres what my pull will request will show when using Thredds and the Geoserver plugin: 

screen shot 2015-10-27 at 12 02 06 pm
Otherwise it loads as before. Job done.

**Comment by danfruehauf** [comment]
@dnahodil OK if I leave it with you to review?

I have quite a bit on my plate now...

**Comment by dnahodil** [comment]
Yeah. Code all looked good to me other than that one suggestion.

**Pull request merged**
